"""Added check-in and cancellation fields

Revision ID: 068e186db8d2
Revises: 9e2ca5bd167b
Create Date: 2025-03-21 21:11:51.881577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068e186db8d2'
down_revision = '9e2ca5bd167b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_canceled', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_column('is_canceled')
        batch_op.drop_column('is_checked_in')

    # ### end Alembic commands ###
